#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

commit_types="(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|wip)"
convetional_commit_regex="^${commit_types}(\([a-z \-]+\))?!?: .+$"

commit_message=$(cat "$1")


if [[ "$commit_message" =~ $convetional_commit_regex ]]; then
   exit 0
fi

echo "The commit message does not meet commit standards"
echo "An example of a valid message is: "
echo "  feat: update modal fields"

exit 1